/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[6];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints -1 
#define nSplines 0 
#define precision 1e-05 

#define beta parms[0] 
 #define k parms[1] 
 #define b2 parms[2] 
 #define y0_0 parms[3] 
 #define y1_0 parms[4] 
 #define y2_0 parms[5] 
#define tmin range[0]
#define tmax range[1]


void Osc_3_initmod(void (* odeparms)(int *, double *)) {
	 int N=6;
	 odeparms(&N, parms);
}

void Osc_3_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void Osc_3_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = beta/(1.0+pow((y[2]/k),3.0))-b2*y[0];
 	 ydot[1] = beta/(1.0+pow((y[0]/k),3.0))-b2*y[1];
 	 ydot[2] = beta/(1.0+pow((y[1]/k),3.0))-b2*y[2];

}

