/** Code auto-generated by cOde 1.1.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[6];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints -1 
#define nSplines 0 
#define precision 1e-05 

#define b1 parms[0] 
 #define a1 parms[1] 
 #define b2 parms[2] 
 #define a2 parms[3] 
 #define y0_0 parms[4] 
 #define y1_0 parms[5] 
#define tmin range[0]
#define tmax range[1]


void Alon_damped_initmod(void (* odeparms)(int *, double *)) {
	 int N=6;
	 odeparms(&N, parms);
}

void Alon_damped_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void Alon_damped_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = -b1*y[1]-a1*y[0];
 	 ydot[1] = b2*y[0]-a2*y[1];

}

